apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodeapp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodeapp
    app.kubernetes.io/part-of: test-application
  name: nodeapp
  namespace: hacbs-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nodeapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: nodeapp
    spec:
      containers:
      - image: quay.io/karthik_jk/nodeapp@sha256:3b92411424ee5d3fb5957ff6611436f8f7cb828f70babad7aa55dc4c43553bae
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
